image: Ubuntu

environment:
  nodejs_version: "14"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

# deploy_script:

notifications:
  - provider: Email
    to:
      - fff26@mail.ru
    on_success: never
    on_failure: always
